drop table IF EXISTS  ago_string;
drop table IF EXISTS  ago_blob;
drop table IF EXISTS  ago_class;
drop table IF EXISTS  ago_function;
drop table IF EXISTS  ago_instance;
drop table IF EXISTS  ago_frame;
drop table IF EXISTS  ago_runspace;

create table ago_runspace(
	id 	bigint primary key,
	application	bigint,
	native_host_class text,		-- native host class which can spawn this runspace

	curr_frame_table    varchar(1024),
	curr_frame_id	   bigint,

	result_slots 	json,
	running_state 	smallint,

	exception_id    bigint,   --ago_instance.id

	pausing_parents		bigint[],		-- ago_runspace.id
	forked_runspaces    bigint[],


	parent_runspace			bigint

	-- UnhandledException
);

create table ago_string (
  id                            bigint,
  application                   int not null,
  index                         int not null,
  value                         text,
  constraint pk_ago_string primary key (application,index)
);

create table ago_blob (
  id                            bigint,
  application                   int not null,
  index                         int not null,
  data                          bytea,
  constraint pk_ago_blob primary key (application,index)
);

create table ago_class (
  id                            bigint generated by default as identity not null,

  class_id                      int, -- may duplicate for parent_scope different, the classloader should load items has none parent_scope

  application                   bigint,
  ago_class                     text,

  parent_scope_id               bigint,
  parent_scope_class            text,

  creator_id                    bigint,
  creator_class                 text,
  fullname                      text,
  class_type                    int,
  has_slots_creator             bool,
  modifiers                     int,
  super_class                   text,
  interfaces                    text[],
  children                      text[],
  methods                       text[],
  parent                        text,
  permit_class                  text,
  parameterized_base_class      text,
  slots                         json,
  name                          varchar(1024),
  fields                        json[],
  slotDefs                      json[],
  concrete_type_info            json,
  source_location               json,
  constraint pk_ago_class primary key (id)
);

create table ago_function (
  id                            bigint generated by default as identity not null,
  application                   bigint,
  ago_class                     text,
  parent_scope_id               bigint,
  parent_scope_class            text,
  creator_id                    bigint,
  creator_class                 text,
  fullname                      text,
  class_id                      int,
  class_type                    int,
  has_slots_creator             bool,
  modifiers                     int,
  super_class                   text,
  interfaces                    text[],
  children                      text[],
  methods                       text[],
  parent                        text,
  permit_class                  text,
  parameterized_base_class      text,
  code                          int[],
  native_function_result_slot   int,
  slots                         json,
  name                          varchar(1024),
  fields                        json[],
  slotDefs                      json[],
  concrete_type_info            json,
  source_location               json,
  variables                     json[],
  parameters                    json[],
  switch_tables                 json[],
  try_catch_items               json[],
  source_map_entries            json[],
  native_function_entrance      varchar(1024),
  result_type                   json,
  constraint pk_ago_function primary key (id)
);

create table ago_instance (
  id                            bigint generated by default as identity not null,
  application                   bigint,
  ago_class                     text,
  parent_scope_id               bigint,
  parent_scope_class            text,
  creator_id                    bigint,
  creator_class                 text,
  slots                         json,
  payload						json,
  constraint pk_ago_instance primary key (id)
);

create table ago_frame (
  id                            bigint generated by default as identity not null,
  application                   bigint,
  ago_class                     text,
  parent_scope_id               bigint,
  parent_scope_class            text,
  creator_id                    bigint,
  creator_class                 text,
  caller_id                     bigint,
  caller_class                  text,

  suspended					bool,
  state                         int,

  pc                            int,
  receiver_slot                 int,
  exception_id                  bigint,
  exception_class               text,
  runspace                      text,
  slots                         json,
  payload						json,


  is_entrance					bool,		-- create an EntraceFrame to wrap this call frame
  is_async_entrance			    bool,


  constraint pk_ago_frame primary key (id)
);

